development:
  bucket: marsala_test
  access_key_id: AKIAIZM4UXBWSTZ5FEPA
  secret_access_key: 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
test:
  bucket: bucket-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  bucket: marsala_uploads
  access_key_id: AKIAIZM4UXBWSTZ5FEPA
  secret_access_key: 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
